/*
  # Create Ticket from Automation Layer - Database Function
  
  This function allows Make (automation layer) to create tickets directly via Supabase REST API
  without needing Edge Functions or CLI.
  
  Note: Rule engine processing will happen when the ticket is created through this function
  via a database trigger or when the application fetches the ticket.
*/

-- Create function to handle ticket creation from automation layer
CREATE OR REPLACE FUNCTION create_ticket_from_automation(
  p_issue text,
  p_location text,
  p_category text,
  p_priority text,
  p_user_name text,
  p_chat_id text,
  p_tenant_id uuid,
  p_designation text DEFAULT NULL,
  p_department text DEFAULT NULL,
  p_type text DEFAULT 'Maintenance',
  p_building text DEFAULT NULL,
  p_floor text DEFAULT NULL,
  p_room text DEFAULT NULL
)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_user_id uuid;
  v_ticket_id uuid;
  v_ticket_number text;
  v_chat_id_numeric numeric;
  v_full_location text;
BEGIN
  -- Validate priority
  IF p_priority NOT IN ('critical', 'high', 'medium', 'low') THEN
    RETURN json_build_object(
      'success', false,
      'error', 'Invalid priority. Must be one of: critical, high, medium, low'
    );
  END IF;

  -- Convert chat_id from text to numeric (telegram_chat_id column is numeric)
  BEGIN
    v_chat_id_numeric := p_chat_id::numeric;
  EXCEPTION
    WHEN OTHERS THEN
      RETURN json_build_object(
        'success', false,
        'error', format('Invalid chat_id format: %s. Must be a numeric value.', p_chat_id)
      );
  END;

  -- Find user by chat_id
  -- telegram_chat_id is numeric, so compare numeric to numeric
  SELECT id INTO v_user_id
  FROM users
  WHERE (
    telegram_chat_id = v_chat_id_numeric
    OR telegram_user_id = p_chat_id  -- Also check telegram_user_id (text) as fallback
  )
    AND tenant_id = p_tenant_id
    AND is_active = true
  LIMIT 1;

  IF v_user_id IS NULL THEN
    RETURN json_build_object(
      'success', false,
      'error', format('User not found with chat_id: %s in tenant: %s', p_chat_id, p_tenant_id)
    );
  END IF;

  -- Combine location details (building, floor, room) into location field
  -- Format: "location, Building: X, Floor: Y, Room: Z" or just "location" if no details
  v_full_location := trim(p_location);
  
  -- Append building if provided
  IF p_building IS NOT NULL AND trim(p_building) != '' THEN
    v_full_location := v_full_location || ', Building: ' || trim(p_building);
  END IF;
  
  -- Append floor if provided
  IF p_floor IS NOT NULL AND trim(p_floor) != '' THEN
    v_full_location := v_full_location || ', Floor: ' || trim(p_floor);
  END IF;
  
  -- Append room if provided
  IF p_room IS NOT NULL AND trim(p_room) != '' THEN
    v_full_location := v_full_location || ', Room: ' || trim(p_room);
  END IF;

  -- Create ticket (ticket_number will be auto-generated by trigger)
  INSERT INTO tickets (
    title,
    description,
    category,
    priority,
    type,
    location,
    complainant_id,
    tenant_id,
    status,
    created_at,
    updated_at
  ) VALUES (
    trim(p_issue),
    trim(p_issue),
    trim(p_category),
    p_priority,
    COALESCE(trim(p_type), 'Maintenance'),
    v_full_location,
    v_user_id,
    p_tenant_id,
    'open',
    now(),
    now()
  )
  RETURNING id, ticket_number INTO v_ticket_id, v_ticket_number;

  -- Return success with ticket details
  RETURN json_build_object(
    'success', true,
    'ticket_id', v_ticket_id,
    'ticket_number', v_ticket_number,
    'message', 'Ticket created successfully'
  );

EXCEPTION
  WHEN OTHERS THEN
    RETURN json_build_object(
      'success', false,
      'error', 'Failed to create ticket: ' || SQLERRM
    );
END;
$$;

-- Grant execute permission
GRANT EXECUTE ON FUNCTION create_ticket_from_automation TO authenticated;
GRANT EXECUTE ON FUNCTION create_ticket_from_automation TO anon;

-- Add comment
COMMENT ON FUNCTION create_ticket_from_automation IS 'Creates a ticket from automation layer (Make/Integromat). Called via Supabase REST API RPC endpoint. Handles telegram_chat_id as numeric type.';

-- Refresh schema cache (if supported)
NOTIFY pgrst, 'reload schema';

